Run sudo cephadm shell from the Standalone VM
openstack-k8s-operators/data-plane-adoption pull request #161
Opened 2023-09-20 09:23 UTC by matbu

2023-09-20 11:26 UTC, jistr commented
+1 on that edit but i think we were mainly interested in the other occurrence of the `cephadm shell` command which is in the "Create a workload to adopt" section:

https://openstack-k8s-operators.github.io/data-plane-adoption/contributing/development_environment/#create-a-workload-to-adopt

2023-09-20 14:39 UTC, jistr requested changes
(commented above)

2023-09-27 14:47 UTC, jistr approved these changes
The other part has been done in #163, so we can merge this.

2023-10-04 10:26 UTC, fao89 approved these changes

2023-10-04 10:26 UTC, merged