Adding basic pre-commit to the repo
openstack-k8s-operators/data-plane-adoption pull request #440
Opened 2024-05-06 09:34 UTC by jpodivin

Checks include basic stylewq and ansible-lint
Ansible-lint entry point includes override for the ANSIBLE_ROLES_PATH var, to ensure repo only roles load at runtime.

2024-05-09 07:48 UTC, jistr commented
Should we also add `pre-commit run --all-files` into the lint CI job, and maybe a mention of `pre-commit install` into https://openstack-k8s-operators.github.io/data-plane-adoption/dev/#_tests ?

Any test that is not enforced by the CI will get broken eventually i think :)

2024-05-09 12:39 UTC, jpodivin commented
> Should we also add `pre-commit run --all-files` into the lint CI job, and maybe a mention of `pre-commit install` into https://openstack-k8s-operators.github.io/data-plane-adoption/dev/#_tests ?
> 
> Any test that is not enforced by the CI will get broken eventually i think :)

PR has expanded considerably due to the CI integration. But I've minimized changes to actually executable code by skipping bash checks for all ".bash" files. It seems to me that at least some of them are just templates.

2024-05-10 14:10 UTC, fao89 approved these changes

2024-05-15 12:27 UTC, jistr requested changes
Thanks, i noticed two spots where this accidentally reverts recent changes, but other than that LGTM

2024-05-15 12:27 UTC, jistr commented on docs_user/assemblies/assembly_reviewing-the-openstack-control-plane-configuration.adoc
> +//kgilliga: Should we use this link in the downstream guide?
This is reverting a recent fix

2024-05-15 12:27 UTC, jistr commented on docs_user/modules/proc_performing-a-fast-forward-upgrade-on-compute-services.adoc
> -
Ditto this is a revert

2024-05-15 12:27 UTC, jistr commented on docs_user/modules/proc_performing-a-fast-forward-upgrade-on-compute-services.adoc
> -
It's not visible in the "discussion" view on the PR but if you open the file detail it will be visible what it's removing.

2024-05-15 15:50 UTC, jistr approved these changes
:+1: Thank you

2024-05-15 15:51 UTC, merged