Remove section about stopping certmonger
openstack-k8s-operators/data-plane-adoption pull request #473
Opened 2024-05-29 12:33 UTC by xek

Depends-On: openstack-k8s-operators/edpm-ansible#663

2024-05-30 13:45 UTC, jistr approved these changes

2024-06-14 10:22 UTC, marios reviewed
looks ok per the title, but the immediate question is 'why?'
i mean, please consider including more information in the commit message to give some more context about the change and why you proposed it

2024-06-14 13:48 UTC, klgill approved these changes

2024-06-14 13:49 UTC, klgill commented
This LGTM. Ideally, I'd like to check the doc output to make sure there are no formatting issues, but the check is taking a while.

2024-06-14 15:04 UTC, xek commented
recheck

2024-06-14 19:52 UTC, xek commented
The last run failed on tripleo-cleanup-tripleo-cleanup-openstack ansibleee job, but I can't find the pod logs for that job

2024-06-14 20:28 UTC, xek commented
I think I reproduced the CI failure locally - it looks unrelated to this patch. It fails on TASK [osp.edpm.edpm_tripleo_cleanup : Stop and disable tripleo services] with "Could not find the requested service tripleo_neutron_l3_agent.service: host" and "Could not find the requested service tripleo_neutron_ovs_agent.service: host"

2024-06-14 20:50 UTC, xek commented
recheck

2024-06-15 05:52 UTC, xek commented
recheck

2024-06-15 19:14 UTC, xek commented
recheck

2024-06-16 21:13 UTC, xek commented
recheck

2024-06-17 06:43 UTC, marios commented
the no-ceph job is failing like https://logserver.rdoproject.org/73/473/775abd6d7d6247adf77fff2f8bcf2aad377d697a/github-check/data-plane-adoption-osp-17-to-extracted-crc-minimal-no-ceph/8f68e86/controller/data-plane-adoption-tests-repo/data-plane-adoption/tests/logs/test_minimal_out_2024-06-16T18:33:25EDT.log 

```
TASK [dataplane_adoption : Wait for the deployment to finish] ******************

...

echo 'There are failed AnsibleEE jobs: tripleo-cleanup-tripleo-cleanup-openstack'", "+ exit 1"], "stdout": "There are failed AnsibleEE jobs: tripleo-cleanup-tripleo-cleanup-openstack", "stdout_lines": ["There are failed AnsibleEE jobs: tripleo-cleanup-tripleo-cleanup-openstack


```


and looking a bit closer at pod logs, in pod logs via https://logserver.rdoproject.org/73/473/775abd6d7d6247adf77fff2f8bcf2aad377d697a/github-check/data-plane-adoption-osp-17-to-extracted-crc-minimal-no-ceph/8f68e86/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/sos-reports/_all_nodes/sosreport-crc-pjmnl-master-0-UntarWithArg-i.tar.xz 

```
2024-06-16T23:08:29.465763082+00:00 stdout F TASK [osp.edpm.edpm_install_certs : Backup certificate requests] ***************

2024-06-16T23:08:29.637362504+00:00 stdout F [0;31m    "msg": "Could not find or access '/var/lib/certmonger/requests' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src
```

This seems like  a new issue, but not sure if related to this patch (don't think so, but unsure).

2024-06-17 06:45 UTC, marios requested changes
can we please hold merge until we can confirm latest 'certmonger' issue ... it so far only seems to hit this patch? https://review.rdoproject.org/zuul/builds?job_name=data-plane-adoption-osp-17-to-extracted-crc-minimal-no-ceph&skip=0

2024-06-17 07:33 UTC, xek commented
> the no-ceph job is failing like https://logserver.rdoproject.org/73/473/775abd6d7d6247adf77fff2f8bcf2aad377d697a/github-check/data-plane-adoption-osp-17-to-extracted-crc-minimal-no-ceph/8f68e86/controller/data-plane-adoption-tests-repo/data-plane-adoption/tests/logs/test_minimal_out_2024-06-16T18:33:25EDT.log
> 
> ```
> TASK [dataplane_adoption : Wait for the deployment to finish] ******************
> 
> ...
> 
> echo 'There are failed AnsibleEE jobs: tripleo-cleanup-tripleo-cleanup-openstack'", "+ exit 1"], "stdout": "There are failed AnsibleEE jobs: tripleo-cleanup-tripleo-cleanup-openstack", "stdout_lines": ["There are failed AnsibleEE jobs: tripleo-cleanup-tripleo-cleanup-openstack
> ```
> 
> and looking a bit closer at pod logs, in pod logs via https://logserver.rdoproject.org/73/473/775abd6d7d6247adf77fff2f8bcf2aad377d697a/github-check/data-plane-adoption-osp-17-to-extracted-crc-minimal-no-ceph/8f68e86/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/sos-reports/_all_nodes/sosreport-crc-pjmnl-master-0-UntarWithArg-i.tar.xz
> 
> ```
> 2024-06-16T23:08:29.465763082+00:00 stdout F TASK [osp.edpm.edpm_install_certs : Backup certificate requests] ***************
> 
> 2024-06-16T23:08:29.637362504+00:00 stdout F �[0;31m    "msg": "Could not find or access '/var/lib/certmonger/requests' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src
> ```
> 
> This seems like a new issue, but not sure if related to this patch (don't think so, but unsure).

This is fixed by https://github.com/openstack-k8s-operators/edpm-ansible/pull/680 (it's in the depends-on), so looks like it's not being deployed with this change.

2024-06-17 07:38 UTC, cescgina commented
@xek @marios that's weird, zuul it's really not picking up the depends-on:
```
      items:
      - branch: main
        change: '473'
        change_url: https://github.com/openstack-k8s-operators/data-plane-adoption/pull/473
        patchset: 775abd6d7d6247adf77fff2f8bcf2aad377d697a
        project:
          canonical_hostname: github.com
          canonical_name: github.com/openstack-k8s-operators/data-plane-adoption
          name: openstack-k8s-operators/data-plane-adoption
          short_name: data-plane-adoption
          src_dir: src/github.com/openstack-k8s-operators/data-plane-adoption
      job: data-plane-adoption-osp-17-to-extracted-crc-minimal-no-ceph
      jobtags: []
      max_attempts: 1
  ```
the edpm-ansible patch should be in the `items` list, but it's not https://logserver.rdoproject.org/73/473/775abd6d7d6247adf77fff2f8bcf2aad377d697a/github-check/data-plane-adoption-osp-17-to-extracted-crc-minimal-no-ceph/8f68e86/zuul-info/inventory.yaml

2024-06-17 07:44 UTC, xek commented
BTW not all runs with the failed AnsibleEE jobs: tripleo-cleanup-tripleo-cleanup-openstack failed with the same error, some of those runs fail in TASK [osp.edpm.edpm_tripleo_cleanup : Stop and disable tripleo services] with "Could not find the requested service tripleo_neutron_l3_agent.service: host" and "Could not find the requested service tripleo_neutron_ovs_agent.service: host"

2024-06-17 08:50 UTC, xek commented
recheck https://github.com/openstack-k8s-operators/edpm-ansible/pull/680 has merged

2024-06-17 12:16 UTC, merged