Remove download-cache-openstack service
openstack-k8s-operators/data-plane-adoption pull request #505
Opened 2024-06-25 11:15 UTC by archana203

During Dataplane adoption, download-cache service tries to update libvirt related packages which is not needed.

Resolves: OSPRH-7874

2024-06-26 12:22 UTC, bogdando commented
Does this fix a regression? this used to work w/o issues so far?

2024-06-26 13:28 UTC, jistr submitted a review, later dismissed
LGTM pending a CI pass. For reviewers' context: this is aiming to fix this bug https://issues.redhat.com/browse/OSPRH-7874

2024-06-26 13:36 UTC, bogdando commented
I think we need the latest openstack-selinux and latest libvirt during adoption?

@SeanMooney

2024-06-26 14:44 UTC, SeanMooney commented
so libvirt is not installed on the host pre-adoption and it is installed on the host during adoption as part of the greenfield deployment

the download-cache just pre-downloads the package that will be installed by edpm_libvirt during adoption so I don't think this will help.
i would expect this to just delay the package install slightly.

repo config is meant to be done via bootstrap so by the time download-cache or edpm_libvirt run the repo/subscription management is already done so neither role interact with subscription manager.

2024-06-27 11:44 UTC, bogdando requested changes
please see above

2024-06-28 17:46 UTC, archana203 commented
Based on the discussion, this PR is not valid for the issue. Closing it.

2024-06-28 17:46 UTC, closed without merging