Extend mon label to CephStorage nodes during mon migration
openstack-k8s-operators/data-plane-adoption pull request #591
Opened 2024-09-09 06:42 UTC by fmount

When `mons` are migrated we can't risk to lose quorum during the replacement procedure. For this reason this patch adds a step in the mon migration  to extend the `mon` label to the rest of `CephStorage` nodes (target nodes hosting `OSDs`). By doing this we can make sure temporary mons are deployed, preserving the quorum during the entire process.

2024-09-09 06:45 UTC, fmount commented
@klgill this is already implemented in the testsuite [1].

[1] https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/tests/roles/ceph_migrate/tasks/rbd.yaml#L48-L55

2024-09-09 13:58 UTC, klgill commented on docs_user/modules/proc_migrating-mon-from-controller-nodes.adoc
> +  never lose quorum during the migration process
```suggestion
. Extend the `mon` label to the rest of the {Ceph} target nodes to ensure that you never lose quorum during the migration process:
```

2024-09-09 13:59 UTC, klgill requested changes
@fmount I made some minor changes.

2024-09-09 14:10 UTC, fmount commented on docs_user/modules/proc_migrating-mon-from-controller-nodes.adoc
> +  never lose quorum during the migration process
Done (thank you :D)

2024-09-10 06:15 UTC, fmount commented
@klgill @jistr let me know if you're happy with this and we can merge this missing step in the doc.

2024-09-10 11:21 UTC, jistr approved these changes

2024-09-10 11:24 UTC, jistr commented
Katie's review was incorporated, merging.

2024-09-10 11:24 UTC, merged