Remove old cinder-backup and cinder-scheduler services
openstack-k8s-operators/data-plane-adoption pull request #594
Opened 2024-09-10 04:36 UTC by rajathere

After adoption, we create new services for cinder-scheduler and cinder-backup but we don't clean up the old service records resulting in them being shown up in the service list output as down.

+------------------+------------------------+------+---------+-------+----------------------------+
| Binary           | Host                   | Zone | Status | State | Updated At                  |
+------------------+------------------------+------+---------+-------+----------------------------+
| cinder-scheduler | standalone.localdomain | nova | enabled | down | 2024-08-22T11:56:04.000000  |
| cinder-backup    | standalone.localdomain | nova | enabled | down | 2024-08-22T11:56:04.000000  |
| cinder-volume    | hostgroup@tripleo_ceph | nova | enabled | up   | 2024-08-22T12:56:07.000000  |
| cinder-scheduler | cinder-scheduler-0     | nova | enabled | up   | 2024-08-22T12:56:07.000000  |
| cinder-backup    | cinder-backup-0        | nova | enabled | up   | 2024-08-22T12:56:08.000000  |
+------------------+------------------------+------+---------+-------+----------------------------+

This is incorrect and leads to bad indication that there is something wrong with the deployment. As mentioned in the adoption doc[1] Step 3, we should clean up the old cinder-backup and cinder-scheduler services which this patch aims to address.

[1] https://openstack-k8s-operators.github.io/data-plane-adoption/user/index.html#deploying-the-block-storage-services_preparing-block-storage

2024-09-10 10:08 UTC, rajathere commented
recheck

adoption-standalone-to-crc-ceph passed with expected results
https://logserver.rdoproject.org/94/594/d0b512ba2cfa8690c688a5594b77dcf12ed9ff48/github-check/adoption-standalone-to-crc-ceph/4043602/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/ctlplane/cinder/service_list

adoption-standalone-to-crc-no-ceph failed with unrelated error to Prometheus

FAILED - RETRYING: [localhost]: wait for prometheus metric storage to start up (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 60, "changed": true, "cmd": "set -euxo pipefail\n\n\noc get pod --selector=prometheus=metric-storage -o jsonpath='{.items[0].status.phase}{\"\\n\"}' | grep Running\n", "delta": "0:00:00.157808", "end": "2024-09-10 05:12:39.951459", "msg": "non-zero return code", "rc": 1, "start": "2024-09-10 05:12:39.793651", "stderr": "+ oc get pod --selector=prometheus=metric-storage -o 'jsonpath={.items[0].status.phase}{\"\\n\"}'\n+ grep Running\nerror: error executing jsonpath \"{.items[0].status.phase}{\\\"\\\\n\\\"}\": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:\n\ttemplate was:\n\t\t{.items[0].status.phase}{\"\\n\"}\n\tobject given to jsonpath engine was:\n\t\tmap[string]interface {}{\"apiVersion\":\"v1\", \"items\":[]interface {}{}, \"kind\":\"List\", \"metadata\":map[string]interface {}{\"resourceVersion\":\"\"}}", "stderr_lines": ["+ oc get pod --selector=prometheus=metric-storage -o 'jsonpath={.items[0].status.phase}{\"\\n\"}'", "+ grep Running", "error: error executing jsonpath \"{.items[0].status.phase}{\\\"\\\\n\\\"}\": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:", "\ttemplate was:", "\t\t{.items[0].status.phase}{\"\\n\"}", "\tobject given to jsonpath engine was:", "\t\tmap[string]interface {}{\"apiVersion\":\"v1\", \"items\":[]interface {}{}, \"kind\":\"List\", \"metadata\":map[string]interface {}{\"resourceVersion\":\"\"}}"], "stdout": "", "stdout_lines": []}

2024-09-11 05:03 UTC, rajathere commented
Verified that it works
https://logserver.rdoproject.org/94/594/d0b512ba2cfa8690c688a5594b77dcf12ed9ff48/github-check/adoption-standalone-to-crc-ceph/03ef12b/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/ctlplane/cinder/service_list

+------------------+------------------------+------+---------+-------+----------------------------+
| Binary           | Host                   | Zone | Status  | State | Updated At                 |
+------------------+------------------------+------+---------+-------+----------------------------+
| cinder-volume    | hostgroup@tripleo_ceph | nova | enabled | up    | 2024-09-10T12:51:50.000000 |
| cinder-scheduler | cinder-scheduler-0     | nova | enabled | up    | 2024-09-10T12:51:50.000000 |
| cinder-backup    | cinder-backup-0        | nova | enabled | up    | 2024-09-10T12:51:49.000000 |
+------------------+------------------------+------+---------+-------+----------------------------+

2024-09-13 12:06 UTC, jistr requested changes
This needs a solution in the documentation too, and what we do in docs and tests should be the same. Note that in the docs we cannot use Ansible, so likely we should have a solution that uses Bash piping or Bash variables instead of Ansible registered variables, and then we can run the full snippet in tests too.

A good way to arrive to a mergeable solution is working on the docs first ("how can the user achieve this goal in their terminal?") and then copying the result into tests.

Example usage of Bash piping and variables can be seen in other procedures, e.g. https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/docs_user/modules/proc_migrating-databases-to-mariadb-instances.adoc

Feel free to ping if you'd like some more clarification/detail on anything.

2024-09-16 10:47 UTC, Akrog commented
> This needs a solution in the documentation too, and what we do in docs and tests should be the same. Note that in the docs we cannot use Ansible, so likely we should have a solution that uses Bash piping or Bash variables instead of Ansible registered variables, and then we can run the full snippet in tests too.
> 
> A good way to arrive to a mergeable solution is working on the docs first ("how can the user achieve this goal in their terminal?") and then copying the result into tests.
> 
> Example usage of Bash piping and variables can be seen in other procedures, e.g. https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/docs_user/modules/proc_migrating-databases-to-mariadb-instances.adoc
> 
> Feel free to ping if you'd like some more clarification/detail on anything.

Hi,

Current docs and ansible are out of sync right now, and this PR is trying to make them be in sync.

You can see that the deletion of the services is [described in the existing documentation](https://github.com/openstack-k8s-operators/data-plane-adoption/blob/4c616f58850888edd2fbf4f44e526620b7b88269/docs_user/modules/proc_adopting-the-block-storage-service.adoc?plain=1#L122), and this PR is implementing it, so there's no need to update the docs.

2024-09-17 14:29 UTC, jistr commented
Ah makes sense, and now i can see Rajat already mentioned it, i just didn't read carefully. Sorry for the confusion guys :). 

We like to to do copy-pastable snippets from docs to tests but it's not a blocker. Merging, thanks :)

2024-09-17 14:30 UTC, jistr approved these changes

2024-09-17 14:30 UTC, merged