Renaming network related variables to align with edpm naming scheme
openstack-k8s-operators/data-plane-adoption pull request #64
Opened 2023-06-29 14:18 UTC by jpodivin

The variables `neutron_public_interface_name` and `neutron_physical_bridge_name` have been renamed in edpm-ansible collection. This change hasn't been propagated correctly however. Therefore all the other occurrences have to be changed, to make sure that the role will affect deployment as requested.  
 
Please exercise caution while reviewing this PR. There is a considerable chance of new bugs being introduced as side effects.

https://github.com/openstack-k8s-operators/edpm-ansible/pull/201

2023-06-29 14:20 UTC, rebtoor reviewed
+2 for me

2023-06-30 08:08 UTC, jpodivin commented
recheck

2023-07-11 09:19 UTC, jistr requested changes

2023-07-11 09:19 UTC, jistr commented on docs/contributing/development_environment_examples/standalone.j2
> +      name: {{ edpm_network_config_interface_name }}
This file is being used by TripleO Wallaby standalone deployment. AFAICT chanigng the name here would break the initial deployment.

2023-07-11 09:19 UTC, jistr commented on docs/ceph/ceph_rgw.md
> +  name: {{ edpm_network_config_bridge_name }}
This file is being passed into `openstack overcloud node provision` command. AFAICT it does not use the EDPM naming and changing the variable name here would result in breakage.

2023-07-11 09:19 UTC, jistr commented on docs/openstack/edpm_adoption.md
> +              edpm_network_config_interface_name: eth1
As i see the changes haven't been merged in EDPM yet [1][2] so we should hold off merging these for now.

[1] https://github.com/openstack-k8s-operators/dataplane-operator/blob/d5132138cb07661f2658c6e86a7864dd2d9ede93/config/samples/dataplane_v1beta1_openstackdataplane.yaml#L80-L81
[2] https://github.com/openstack-k8s-operators/edpm-ansible/pull/201

2023-09-13 08:42 UTC, jistr commented
I see the neutron vars were not renamed in the end? [1] Can we close this PR?

[1] https://github.com/openstack-k8s-operators/edpm-ansible/pull/201/files

2023-09-21 07:45 UTC, closed without merging