Use multiple DNS solvers for DNSMasq CR
openstack-k8s-operators/data-plane-adoption pull request #656
Opened 2024-10-14 15:55 UTC by bogdando

Align different methods of specifying and overriding DNS resolvers.

No longer patch openstack CR by replacing dns server record to set the correct value for the environment. Instead, define server entries for dnsmasq, when creating oscp/openstack CR.

Use upstream_dns var to provide a 1st entry there, which defaults to CRC machine IP.
After this change, we no longer need to hack it in ci-framework for adoption testing infra setup:

https://github.com/openstack-k8s-operators/ci-framework/blob/ bc7fc12d0a60b44fc34a89aff08765b5e9cdc8c0/hooks/playbooks/fetch _compute_facts.yml#L102

Use dns_server_ip to provide a 2nd entry, which defaults to a hypervisor IP (assuming CRC is running there as a VM).

By using both server entries, make sure that resolving of OCP hosted and external resources always work for EDPM nodes.

This also enables adoption CI jobs to start configuring network on EDPM nodes, as soon as os-net-config allows applying DNS server in resolv.conf without restarting network bridges. Real deployments will always configure EDPM nodes' network and we should do the same in CI jobs, instead of providing that via infra setup in CI-only roles.

Update docs to explain use cases for multiple DNS servers.

2024-10-14 16:00 UTC, stuggi requested changes

2024-10-14 16:00 UTC, stuggi commented on docs_user/modules/proc_deploying-backend-services.adoc
> +For external, or other resources on the intranet, you may want to provide additional IP addresses for datacentre DNS resolvers.
192.168.122.1 should be the one which can resolve any other names, either from external (internet) or from services in the datacentre.

2024-10-14 16:01 UTC, stuggi commented on docs_user/modules/proc_deploying-backend-services.adoc
> +including messaging and database services, you should provide IP addresses of OCP master nodes.
also the database services are not exposed to the edpm nodes.

2024-10-15 10:35 UTC, bogdando commented on docs_user/modules/proc_deploying-backend-services.adoc
> +including messaging and database services, you should provide IP addresses of OCP master nodes.
@stuggi  edpm nodes will keep using "the dnsmasq instance on the metallb vip", like the default 192.168.122.80 that we configure. This pull request changes nothing for EDPM nodes. This change is about to change DNSMasq server entries. Today we overwrite it by patching in CI infra tasks. I don't think that is that customers should do. The only entry point for them should be the oscp CR's dns config. And this change is about that.

2024-10-15 10:46 UTC, stuggi commented on docs_user/modules/proc_deploying-backend-services.adoc
> +including messaging and database services, you should provide IP addresses of OCP master nodes.
check the explanation from @cescgina on slack why that is done for ci

2024-10-15 11:09 UTC, bogdando commented
I see that this change may not be needed, and a datacentre DNS resolver (here it is 192.168.122.1) could be as well the only server key. While .10 is related for our CI infra setup for the extracted CRC

2024-10-15 11:09 UTC, closed without merging