support cinder netapp nfs backend adoption
openstack-k8s-operators/data-plane-adoption pull request #768
Opened 2024-12-17 15:37 UTC by katarimanojk

Add support cinder netapp nfs backend adoption

2025-02-13 17:43 UTC, tosky requested changes

2025-02-13 17:43 UTC, tosky commented on tests/roles/cinder_adoption/files/cinder-volume-ontap-secrets.yaml
> +  ontap-cinder-secrets: |
instead of defining the secret here, it may make sense to extract the required information from the OSP deployment. Barbican did this for example:
https://github.com/openstack-k8s-operators/data-plane-adoption/blob/ef823f2f2c5772fce9e7f04876e0bdfe049deb3a/tests/roles/barbican_adoption/tasks/main.yaml#L6

2025-02-13 17:43 UTC, tosky commented on tests/roles/cinder_adoption/tasks/volume_backend.yaml
> +  when: cinder_volume_backend == 'ontap'
ontap or ontap-nfs ? ontap could provide other protocols too

2025-02-17 09:30 UTC, katarimanojk commented on tests/roles/cinder_adoption/tasks/volume_backend.yaml
> +  when: cinder_volume_backend == 'ontap'
agreed, changed it as ontap-nfs.

2025-02-18 10:55 UTC, katarimanojk commented on tests/roles/cinder_adoption/files/cinder-volume-ontap-secrets.yaml
> +  ontap-cinder-secrets: |
@tosky yeah, i think it can be extracted from OSP deployment , first we need to look at how the secrets section is populated in  /var/lib/config-data/puppet-generated/cinder/etc/cinder/cinder.conf.

2025-06-12 13:07 UTC, katarimanojk commented
This patch is no longer needed

2025-06-12 13:07 UTC, closed without merging