Add IPv6 adoption documentation
openstack-k8s-operators/data-plane-adoption pull request #773
Opened 2024-12-20 13:47 UTC by elvgarrui

This includes steps on how to deploy an environment for adoption and guides to use ipv6.

Resolves: #OSPRH-4223

2025-01-07 17:12 UTC, klgill commented
@fmount Are you looking to merge this PR by a certain date, or just by FR2 GA? This will help me prioritize. Thanks!

2025-01-07 17:16 UTC, fmount commented
> @fmount Are you looking to merge this PR by a certain date, or just by FR2 GA? This will help me prioritize. Thanks!

Hi @klgill, I think @elvgarrui can help on this question. I suppose this is relevant for FR2, but I'll let someone from the networking team to confirm.

2025-01-08 09:12 UTC, elvgarrui commented
Yes, this is relevant for FR2 (In order to support IPv6 adoption) @klgill @fmount Thank you!!

2025-01-08 13:44 UTC, klgill commented
> Yes, this is relevant for FR2 (In order to support IPv6 adoption) @klgill @fmount Thank you!!

Thanks! I think I can start this tomorrow.

2025-01-08 20:29 UTC, klgill commented
@elvgarrui Regarding docs_dev/assemblies/development_environment.adoc, is this procedure eventually going to need to be published in the downstream docs, or is this dev only?

2025-01-09 09:05 UTC, elvgarrui commented
@klgill I think customers would already have their environment so it might not have sense to publish that downstream. However I will check with others for confirmation.

2025-01-09 19:33 UTC, klgill requested changes
@elvgarrui Please see my suggested changes.

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_adopting-image-service-with-block-storage-backend.adoc
> +E.g: `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`
```suggestion
[NOTE]
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_adopting-image-service-with-ceph-backend.adoc
> +E.g: `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`
```suggestion
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_adopting-image-service-with-nfs-backend.adoc
> +E.g: `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`
```suggestion
[NOTE]
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_adopting-image-service-with-object-storage-backend.adoc
> +E.g: `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`
```suggestion
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_adopting-key-manager-service.adoc
> +E.g: `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`
```suggestion
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_adopting-the-block-storage-service.adoc
> +E.g: `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`
```suggestion
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_adopting-the-compute-service.adoc
> +E.g: `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`
```suggestion
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_adopting-the-networking-service.adoc
> +E.g: `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`
```suggestion
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_adopting-the-object-storage-service.adoc
> +E.g: `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`
```suggestion
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_adopting-the-placement-service.adoc
> +E.g: `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`
```suggestion
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_configuring-a-ceph-backend.adoc
> +`mon_host = [v2:[fd00:cccc::100]:3300/0,v1:[fd00:cccc::100]:6789/0]`
```suggestion
If you use IPv6, use brackets for the `mon_host`, as shown in the following example: 
`mon_host = [v2:[fd00:cccc::100]:3300/0,v1:[fd00:cccc::100]:6789/0]`
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_deploying-backend-services.adoc
> +If you are using IPv6, remember to change the load balancer IPs to ones that are correct in your environment.
```suggestion
If you use IPv6, change the load balancer IPs to the IPs in your environment.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_deploying-file-systems-service-control-plane.adoc
> +E.g: `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`
```suggestion
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_deploying-the-bare-metal-provisioning-service.adoc
> +[source,bash]
```suggestion
If you use IPv6, change the load balancer IP to the IP in your environment, for example,
 `metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
+
```

2025-01-09 19:33 UTC, klgill commented on docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
> +If you need to use IPv6, declare `SOURCE_MARIADB_IP` *without* brackets (e.g. `SOURCE_MARIADB_IP=fd00:bbbb::2`)
```suggestion
If you need to use IPv6, declare `SOURCE_MARIADB_IP` without brackets, for example, `SOURCE_MARIADB_IP=fd00:bbbb::2`.
```

2025-01-13 16:02 UTC, booxter requested changes
Some comments, questions, suggestions. Thanks for the work!

2025-01-13 16:02 UTC, booxter commented on docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
> +In case that this command fail, it may be due to the fact that the MariaDB container needs a bit more time. If that happens, you can use a sleep:
This is brittle. Can we not wait for mariadb server service to become Healthy (in k8s API), then talk to it?

2025-01-13 16:02 UTC, booxter commented on docs_user/modules/proc_using-new-subnet-ranges.adoc
> +If you are using IPv6, you can most likely reuse existing subnet ranges, which you can check in the section <<reusing-existing-subnet-ranges_{context}>>.
The intent was - I think - to suggest that in contrast to IPv4, the size of IPv6 subnets in old setup is probably enormous and would satisfy any new requirements for adoption, so there is probably no need to juggle between old and new subnets, as may be more common for IPv4. The edit loses this context.

2025-01-13 18:05 UTC, elvgarrui commented on docs_user/modules/proc_using-new-subnet-ranges.adoc
> +If you are using IPv6, you can most likely reuse existing subnet ranges, which you can check in the section <<reusing-existing-subnet-ranges_{context}>>.
Yes, it was mostly to save time from people who might start reading that section with no actual need.

2025-01-13 18:05 UTC, elvgarrui commented on docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
> +----
No, it runs a command inside of the mariadb-client pod after a small piece of time has passed

2025-01-13 18:06 UTC, elvgarrui commented on docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
> +In case that this command fail, it may be due to the fact that the MariaDB container needs a bit more time. If that happens, you can use a sleep:
Isn't that what the pod does by default before running a command inside of it? I tried for some time to have a proper way to go through this but that was the best that I could find (And with Yatin's help). I did not intend to add this at first since I know it's not clean and it might be  due to slowness of my particular environment, but it also happened to Fiorella so I decided to add this in order to ease the way of anyone else with that problem.

2025-01-13 18:06 UTC, elvgarrui commented on docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
> +. Make sure you are on the `openstack` namespace.
This is general case, would it be better to make a different PR for this? I just wanted to make the clarification to save some time on trial and error,  because anyone that might be doing the entire process will most likely be on the openstack-operator project at this point.

2025-01-13 18:07 UTC, elvgarrui commented on docs_user/modules/proc_migrating-databases-to-mariadb-instances.adoc
> +# If using IPv6, don't declare addresses within brackets
My intention was to make clear that if you use the IPv6 declaration that includes brackets is not used here, which is something I saw some times during this procedure (most present if you need to also declare a port, because it adds an extra ":". I think one example where IPv6 is declare with brackets is on the ceph.conf. [fd00:cccc::100]:3300/0
But now that I'm re reading, maybe this clarification is not needed at all

2025-01-13 18:08 UTC, elvgarrui commented on docs_dev/assemblies/development_environment.adoc
> +On the host:
Hmm I wanted to refer to the main system that is used to deploy everything else inside of it, hence using the word host. The libvirt hypervisor is running there for sure, but the networking configuration is of the whole server. Maybe I could say "On the host where the hypervisor is running" to be as precise as possible?

2025-01-13 18:12 UTC, elvgarrui commented on docs_user/modules/proc_configuring-a-ceph-backend.adoc
> +`mon_host = [v2:[fd00:cccc::100]:3300/0,v1:[fd00:cccc::100]:6789/0]`
done

2025-01-13 18:13 UTC, elvgarrui commented on docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
> +If you need to use IPv6, declare `SOURCE_MARIADB_IP` *without* brackets (e.g. `SOURCE_MARIADB_IP=fd00:bbbb::2`)
done, thanks!

2025-01-14 00:15 UTC, booxter commented on docs_dev/assemblies/development_environment.adoc
> +On the host:
I think "hypervisor" (or "hypervisor host") is a common way of referring to the machine that hosts libvirt machines. I suggest adding a clarifying word like "hypervisor host" here, otherwise "host" may be interpreted as any of the involved machines (e.g. CRC or Compute).

2025-01-14 00:18 UTC, booxter commented on docs_user/modules/proc_migrating-databases-to-mariadb-instances.adoc
> +# If using IPv6, don't declare addresses within brackets
Yeah, I think "ip-address-with-brackets" should be given special treatment because it's tool dependent, while "bracket-less" ip address is the default / assumed variant. (Brackets are not defined by base IPv6 RFC and are not part of an IP address. They are defined for URLs/URIs and may also be used by some tools.)

2025-01-14 00:20 UTC, booxter commented on docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
> +In case that this command fail, it may be due to the fact that the MariaDB container needs a bit more time. If that happens, you can use a sleep:
AFAIU the issue you are trying to handle with the sleep is the fact that mariadb-server is not up when mariadb-client is executed. This is a different pod. So whatever guarantees -client pod `oc exec` call may give in terms of Healthy status would not apply to server pod. That's why I think you should wait for -server service to become Healthy, then call to it using the client pod.

2025-01-24 15:19 UTC, elvgarrui commented on docs_user/modules/proc_migrating-databases-to-mariadb-instances.adoc
> +# If using IPv6, don't declare addresses within brackets
done

2025-01-24 16:42 UTC, booxter commented on docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
> +In case that this command fail, it may be due to the fact that the MariaDB container needs a bit more time. If that happens, you can use a sleep:
Sorry, it's me who misunderstood the intent. Indeed, it's talking to SOURCE_MARIADB_IP at this point. Then I'm not sure what the error you were getting is. Do you have a log so that we can take a look? @elvgarrui

2025-01-24 17:48 UTC, booxter commented on docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
> +. Make sure you are on the `openstack` namespace.
Nah that's fine. Just wanted to make sure we understand the cause. If it's an omission that applies regardless of the IP mode, then I'm ok to include it here, even if having a separate PR would also work.

2025-01-27 13:52 UTC, elvgarrui commented on docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
> +In case that this command fail, it may be due to the fact that the MariaDB container needs a bit more time. If that happens, you can use a sleep:
`oc get events` doesn't return anything interesting, then from `oc logs  mariadb-client -f `  I only see ERROR 2002 `(HY000): Can't connect to MySQL server on 'fd00:bbbb::2' (115)` . I also checked ip route and ip a commands inside the mariadb-client pod. The only thing I can highlight is that `ip a` output changed from:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 
2: eth0@if3113: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default link/ether 0a:58:a5:16:ba:fb brd ff:ff:ff:ff:ff:ff link-netnsid 0 inet6 fd00:abcd:0:1::bf8/64 scope global valid_lft forever preferred_lft forever inet6 fe80::858:a5ff:fe16:bafb/64 scope link valid_lft forever preferred_lft forever
3: net1@if757: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default link/ether 06:85:bc:90:3d:98 brd ff:ff:ff:ff:ff:ff link-netnsid 0 inet6 fd00:bbbb::30/64 scope global tentative valid_lft forever preferred_lft forever inet6 fe80::485:bcff:fe90:3d98/64 scope link tentative valid_lft forever preferred_lft forever
```
to this other values (with sleep 5):
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 
2: eth0@if3111: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default link/ether 0a:58:b3:c5:42:44 brd ff:ff:ff:ff:ff:ff link-netnsid 0 inet6 fd00:abcd:0:1::bf6/64 scope global valid_lft forever preferred_lft forever inet6 fe80::858:b3ff:fec5:4244/64 scope link valid_lft forever preferred_lft forever 
3: net1@if757: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default link/ether 56:a0:4a:bc:72:5a brd ff:ff:ff:ff:ff:ff link-netnsid 0 inet6 fd00:bbbb::30/64 scope global tentative valid_lft forever preferred_lft forever inet6 fe80::54a0:4aff:febc:725a/64 scope link tentative valid_lft forever preferred_lft forever
```
Do you know which other log could be useful?

2025-01-31 17:21 UTC, klgill commented on docs_user/modules/proc_adopting-image-service-with-block-storage-backend.adoc
> +`metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```suggestion
If you use IPv6, change the load balancer IP to the load balancer IP from your environment, for example,
`metallb.universe.tf/loadBalancerIPs:  fd00:bbbb::80`.
```
@elvgarrui A lot of these notes that you added would be better placed after the code as a bullet point. I suggest that you merge this PR (when it's ready), and then I can create a separate doc PR and make those changes.

2025-02-04 11:25 UTC, elvgarrui commented on docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
> +In case that this command fail, it may be due to the fact that the MariaDB container needs a bit more time. If that happens, you can use a sleep:
For now, I'm taking this out to "Focus on the happy path" as suggested by the documentation tips on the contributors page. In any case, the simpler workaround is to just retrieve this from the openstack environment and then copy pasting it on the new env, instead of using a pod.

2025-02-04 14:35 UTC, booxter approved these changes
Thank you for diligently working through comments.

2025-02-04 15:24 UTC, merged